### ISSUE TITLE
Alternative data providers?

### ISSUE THREAD

**Issue by jonafato** [adchari/LedgerStockUpdate#4]
I've noticed that World Trading Data is missing data for a lot of stock symbols I'd expect them to have (e.g. AAPL, FB), and the data returned by the [sample request](https://api.worldtradingdata.com/api/v1/stock?symbol=SNAP,TWTR&api_token=demo) listed in the [documentation](https://www.worldtradingdata.com/documentation#real-time-market-data) has the correct JSON structure but contains mostly null values. Are you open to switching the API used by `LedgerStockUpdate` to a different one, or possibly adding support for multiple API providers? I don't have a particular favorite here, but [Alpha Vantage](https://www.alphavantage.co/) appears to have up-to-date data and a free tier that's more than sufficient for personal ledger use.

**Comment by adchari** [comment]
Yeah I've been having this issue as well recently, sent them an email. They announced that they were going to shut down, then that someone else was buying them and they were staying online. 

I would be open to replacing the API with another, if it continues to be bad.

**Comment by adchari** [comment]
FYI, planning on switching this to use AlphaVantage, since the WorldTradingData API has been non-existent for a while.
